eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  application:
    name: oauth2-client
server:
  port: 8888

security:
  oauth2:
    client:
      client-id: 7d084c00bf6fa58719d1
      client-secret: 0c6cc0c676a1e352853ead840287e0aac94001f3
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      client-authentication-scheme: form
    resource:
      user-info-uri: https://api.github.com/user
      prefer-token-info: false

